# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d57d0ee873a6f384ba29f6c948521c921fee3c9364b19ccafec56c6819bdc20d93c7f076503eeb2591d2f6e4923383e00cb3d1a8c3e8932718056b47c61db35

test:
  secret_key_base: 20af1f638510f2246ae5e208863c1b3b7ef057139cbfee2ef5158222ffd8e21bd66466d649651b9861448af4862f8212f5c748b57ef3af472c56b50b8b26d598

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
